on: pull_request
jobs:
  process-last-commit-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fetch last two commits) of the PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Process files changed in the current commit
        run: |
          changedFiles=$(git diff --name-only $GITHUB_SHA)
          for file in $changedFiles; do
            echo "Processing file: $file"
          done
