on: pull_request
jobs:
  process-last-commit-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (fetch last two commits)
        uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - name: debug
        run: |
          git log --oneline
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
      - name: Process files changed in the current commit
        run: |
          changedFiles=$(git diff --name-only $GITHUB_REF^)
          for file in $changedFiles; do
            echo "Processing file: $file"
          done
