name: Zip example

on:
  push:
    branches:
      - main

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: zip -r build.zip . -x '.git*'
      - run: unzip -l build.zip
